theme: minima
title: Coffee & Gaming
author: Pieter Schreuder
email: pschreuder11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog I talk about all things web development, gaming and coffee. 
  Cant forget coffee.

# social links
twitter_username: None # DO NOT include the @ character, or else the build will fail!
github_username:  Pieter1254 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false# set to false to remove excerpts on the homepage
